CREATE TABLE IF NOT EXISTS SOLUTION
(
  ID         INTEGER PRIMARY KEY AUTOINCREMENT,
  TASK_ID    INTEGER,
  PROBLEM_ID INTEGER,
  ITEMS TEXT NOT NULL,
  FOREIGN KEY (TASK_ID) REFERENCES TASK (ID),
  FOREIGN KEY (PROBLEM_ID) REFERENCES PROBLEM (ID)
);