CREATE TRIGGER IF NOT EXISTS UPDATE_SOLUTION_TIME
  AFTER INSERT
  ON SOLUTION
  FOR EACH ROW
  BEGIN

    UPDATE SOLUTION
    SET TIME = (SELECT TASK.COMPLETED - TASK.STARTED FROM TASK WHERE TASK.ID = SOLUTION.TASK_ID)
    WHERE SOLUTION.ID = NEW.ID
      AND TIME IS NULL;

  END;